"""
Domain Models and Data Structures for Virtual Camera & Optical Image Generation.
Team PHARO — SIH26169
"""

from __future__ import annotations
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field, ConfigDict

from ..world.models import Vector3D


VisibilityReason = Literal["VISIBLE", "BEHIND_CAMERA", "OUT_OF_FOV"]


class CameraIntrinsics(BaseModel):
    """
    Pinhole Camera Optical Intrinsics derived from sensor resolution and FOV.
    Matrix Representation:
      K = [ [fx,  0, cx],
            [ 0, fy, cy],
            [ 0,  0,  1] ]
    """
    fx: float = Field(description="Focal length along X axis in pixels", gt=0.0)
    fy: float = Field(description="Focal length along Y axis in pixels", gt=0.0)
    cx: float = Field(description="Principal point X coordinate in pixels", ge=0.0)
    cy: float = Field(description="Principal point Y coordinate in pixels", ge=0.0)
    width: int = Field(description="Sensor width in pixels", ge=1)
    height: int = Field(description="Sensor height in pixels", ge=1)
    hfov_deg: float = Field(description="Configured horizontal FOV in degrees", gt=0.0, lt=180.0)
    vfov_deg: float = Field(description="Configured vertical FOV in degrees", gt=0.0, lt=180.0)

    def to_matrix(self) -> List[List[float]]:
        """Returns 3x3 intrinsic matrix K."""
        return [
            [self.fx, 0.0, self.cx],
            [0.0, self.fy, self.cy],
            [0.0, 0.0, 1.0],
        ]


class CameraPose(BaseModel):
    """
    Instantaneous 3D pose of the Virtual Camera.
    Position in World Coordinates; Gimbal orientation angles in degrees.
    """
    position: Vector3D = Field(default_factory=Vector3D, description="Camera 3D position in world frame (m)")
    pan_deg: float = Field(default=0.0, description="Gimbal pan angle in degrees (rotation around world Y axis)")
    tilt_deg: float = Field(default=0.0, description="Gimbal tilt angle in degrees (rotation around camera lateral X axis)")

    model_config = ConfigDict(frozen=False)


class ProjectedPoint(BaseModel):
    """
    Continuous 2D image coordinates projected onto focal plane sensor.
    (0, 0) is top-left corner; u: horizontal (0 -> width), v: vertical (0 -> height).
    """
    u: float = Field(description="Horizontal pixel coordinate (0 to width)")
    v: float = Field(description="Vertical pixel coordinate (0 to height)")
    normalized_x: float = Field(description="Normalized camera coordinate X_cam / Z_cam")
    normalized_y: float = Field(description="Normalized camera coordinate Y_cam / Z_cam")


class CameraAngles(BaseModel):
    """
    Apparent angular bearing of optical beacon relative to camera line of sight (boresight).
    """
    azimuth_deg: float = Field(description="Apparent azimuth angle relative to boresight (deg): atan2(X_cam, Z_cam)")
    elevation_deg: float = Field(description="Apparent elevation angle relative to boresight (deg): atan2(Y_cam, sqrt(X_cam^2 + Z_cam^2))")


class CameraVisibility(BaseModel):
    """
    Beacon visibility determination and boundary classification.
    """
    visible: bool = Field(description="True if beacon is in front of camera and inside sensor bounds")
    in_front_of_camera: bool = Field(description="True if Z_camera > 0")
    inside_horizontal_fov: bool = Field(description="True if 0 <= u < width (and Z_camera > 0)")
    inside_vertical_fov: bool = Field(description="True if 0 <= v < height (and Z_camera > 0)")
    reason: VisibilityReason = Field(description="Visibility classification ('VISIBLE', 'BEHIND_CAMERA', 'OUT_OF_FOV')")


class CameraFrame(BaseModel):
    """
    Complete observation frame metadata generated by Virtual Camera at timestamp.
    """
    timestamp: float = Field(description="Simulation timestamp in seconds", ge=0.0)
    width: int = Field(description="Image sensor width in pixels")
    height: int = Field(description="Image sensor height in pixels")
    visible: bool = Field(description="Whether beacon is currently visible in camera sensor")
    camera_position: Vector3D = Field(description="Camera world position")
    camera_orientation: Dict[str, float] = Field(description="Camera orientation: {'pan_deg': float, 'tilt_deg': float}")
    beacon_world_position: Vector3D = Field(description="Ground-truth beacon world position")
    beacon_camera_coordinates: Vector3D = Field(description="Beacon coordinates in camera reference frame (m)")
    projection: ProjectedPoint = Field(description="Projected image-plane pixel coordinates")
    angles: CameraAngles = Field(description="Apparent camera-relative azimuth and elevation")
    visibility: CameraVisibility = Field(description="Detailed visibility diagnostics")
    spot_radius: float = Field(default=2.5, description="Effective radius of rendered beacon spot in pixels")
    spot_intensity: int = Field(default=255, description="Peak 8-bit intensity of rendered beacon spot (0-255)")


class CameraStatus(BaseModel):
    """
    Lifecycle status, optical parameters, and telemetry overview of the Virtual Camera.
    """
    initialized: bool = Field(description="True if virtual camera is initialized")
    width: int = Field(description="Sensor width in pixels")
    height: int = Field(description="Sensor height in pixels")
    horizontal_fov_deg: float = Field(description="Horizontal FOV in degrees")
    vertical_fov_deg: float = Field(description="Vertical FOV in degrees")
    pan_deg: float = Field(description="Current gimbal pan angle in degrees")
    tilt_deg: float = Field(description="Current gimbal tilt angle in degrees")
    intrinsics: CameraIntrinsics = Field(description="Camera intrinsic parameters (fx, fy, cx, cy)")
    current_timestamp: float = Field(description="Current simulation timestamp in seconds")
    scenario_name: str = Field(description="Active scenario configuration title")
    last_frame_visible: Optional[bool] = Field(default=None, description="Visibility status of last captured frame")
